
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Java_Challenge_2024
    ports:
      - "8080:8080"  # Map port 8080 on the host to port 8080 in the container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
